---
title: "P1_Trans_Policy"
author: "Huizenga"
date: "2024-10-07"
output: html_document
---

```{r}
av <- available.packages(filters = list())
av[av[, "Package"] == "ggsflabel", ]
```

```{r}
av[av[, "Package"] == "ggsflabel", "Depends"]
```
```{r}
av[av[, "Package"] == "ggsflabel", "OS_type"]
```


```{r}
library(readxl)
library(dplyr)
library(ggplot2)
#library(ggsflabel)
library(sf)
library(tigris)
library(stringr)
# Get sheet names
sheets <- excel_sheets("P1_Trans_Policy.xlsx")

# Exclude specific sheets by name
sheets_to_read <- sheets[!sheets %in% c("antidiscrim_edu", 
                                        "antidiscrim_uni", 
                                        "antidiscrim_ins", 
                                        "antidiscrim_hous", 
                                        "antidiscrim_pub", 
                                        "antidiscrim_st_emp", 
                                        "religexempt_pro", 
                                        "state_rfra", 
                                        "restrict_munipro")]

all_sheets <- lapply(sheets_to_read, 
                     function(x) read_excel("P1_Trans_Policy.xlsx", 
                                            sheet = x))

# Combine all sheets into one dataset (without removing common columns yet)
combined_data <- bind_rows(all_sheets)
```

```{r}
trans <- combined_data %>%
  rowwise() %>%  # applying functions row by row
  mutate(antidiscrim_score = sum(antidiscrim_edu, 
                                 antidiscrim_ins, 
                                 antidiscrim_hous, 
                                 antidiscrim_pub, 
                                 antidiscrim_st_emp,
                                 antidiscrim_emp)) %>% 
  ungroup()  # ungroup to return to regular dataframe
```

```{r}
trans <- trans %>%
  rowwise() %>% 
  mutate(antiequal_score = sum(religexempt_pro, 
                               state_rfra,
                               restrict_munipro)) %>% 
  ungroup()  
```

```{r}
trans <- trans %>% 
  rowwise() %>% 
  mutate(antidiscrim_per = round(antidiscrim_score / 6, 3))

trans <- trans %>% 
  rowwise() %>% 
  mutate(antiequal_per = round(antiequal_score / 6, 3))

trans <- na.omit(trans) #for some reason i had two observations for each year and state, duplicated
```


```{r}
library(wesanderson)
pal <- wes_palette("Zissou1", 7, type = "continuous")
pal2 <- wes_palette("Zissou1", 4, type = "continuous")
```

```{r}
trans_map <- left_join(usmap, trans, by = c("abbr" = "st"))
```


```{r}
library(sf)
library(dplyr)
library(ggplot2)


# Shift non-contiguous states, add centroid lon/lat values for ggrepel,
# address label placement issue with Mississippi and Alabama
us_states_shifted <- shift_geometry(trans_map) %>%
  mutate(lon = st_coordinates(st_centroid(.))[,1],
         lat = st_coordinates(st_centroid(.))[,2],
         lat = case_when(abbr == "MI" ~ lat - 0.99e5,
                         abbr == "AL" ~ lat + 0.5e5,
                         abbr == "FL" ~ lat + .05e5,
                         abbr == "HI" ~ lon - 200000,
                         .default = lat), 
         lon = case_when(abbr == "MI" ~ lon + .65e5,
                         abbr == "FL" ~ lon + .7e5,
                         abbr == "LA" ~ lon - .5e5,
                         .default = lon)) 

move_labels <- c("CT", "DE", "DC",
                "MA", "MD", "NH", "NJ",
              "RI", "VT")

move_states <- us_states_shifted %>%
  filter(abbr %in% move_labels) %>%
  arrange(lat) %>%
 mutate(xend = 2.2e6,
        yend = case_when(
           abbr == "CT" ~ lat - 0.4e5,
           abbr == "RI" ~ lat + 0.4e5,
           abbr == "VT" ~ lat + 1.2e5,
           abbr == "MA" ~ lat + 0.8e5,
           abbr == "DE" ~ lat + 0.4e5, 
           abbr == "DC" ~ lat - 2.8e5, 
           abbr == "MD" ~ lat - 1.2e5,
           abbr == "NH" ~ lat + 0.4e5, 
           abbr == "NJ" ~ lat + 0.2e5))
```


```{r, fig.height=6.5, fig.width=15}
us_states_shifted24 <- us_states_shifted %>% 
  filter(year == 2024)
# Plot
p1 <- us_states_shifted24 %>% 
  ggplot() +
  geom_sf(aes(fill = as.factor(antidiscrim_score)), color = "black") +
  geom_sf_text(data = filter(us_states_shifted24, !abbr %in% move_labels),
             aes(x = lon, y = lat,
                 label = abbr),
                size = 4) +
  geom_text(data = move_states,
             aes(x = xend, y = yend,
                 label = abbr),
                 size = 4,
                 hjust = 0) +
  geom_segment(data = move_states, 
               aes(x = lon, y = lat, xend = xend, yend = yend),
               colour = "black",
               linewidth = 0.1) +
  scale_fill_manual(values = rev(pal), 
                    name = "Anti-Discrimination Laws", 
                    breaks = 0:6,  
                    labels = c("0 Laws", "1 Law", "2 Laws", "3 Laws", "4 Laws", "5 Laws", "6 Laws")) +
  theme_void() +
  theme(legend.position = "right", 
        legend.background = element_rect(color = "black", fill = "grey90"), 
        legend.margin = margin(10, 5, 10, 5))

p1
```

```{r}
us_states_shifted14 <- us_states_shifted %>% 
  filter(year == 2014)
# Plot
 us_states_shifted14 %>% 
  ggplot() +
  geom_sf(aes(fill = as.factor(antidiscrim_score)), color = "black") +
  geom_sf_text(data = filter(us_states_shifted14, !abbr %in% move_labels),
             aes(x = lon, y = lat,
                 label = abbr),
                size = 2.5) +
  geom_sf_text(data = move_states,
             aes(x = xend, y = yend,
                 label = abbr),
                 size = 2.5,
                 hjust = 0) +
  geom_segment(data = move_states, 
               aes(x = lon, y = lat, xend = xend, yend = yend),
               colour = "black",
               linewidth = 0.1) +
  scale_fill_manual(values = rev(pal), 
                    name = "Anti-Discrimination Laws", 
                    breaks = 0:6,  
                    labels = c("0 Laws", "1 Law", "2 Laws", "3 Laws", "4 Laws", "5 Laws", "6 Laws")) +
  theme_void() +
  theme(legend.position = "right") 
  
```

```{r}
ggsave("p1.pdf", plot = p1, height = 6.5, width = 15)

ggsave("p2.pdf", plot = p2, height = 6.5, width = 15)
```

```{r, fig.height=6.5, fig.width=15}
p2 <- us_states_shifted24 %>% 
  ggplot() +
  geom_sf(aes(fill = as.factor(antiequal_score)), color = "black") +
  geom_sf_text(data = filter(us_states_shifted24, !abbr %in% move_labels),
             aes(x = lon, y = lat,
                 label = abbr),
                size = 4) +
  geom_text(data = move_states,
             aes(x = xend, y = yend,
                 label = abbr),
                 size = 4,
                 hjust = 0) +
  geom_segment(data = move_states, 
               aes(x = lon, y = lat, xend = xend, yend = yend),
               colour = "black",
               linewidth = 0.1) +
  scale_fill_manual(values = pal2, 
                    name = "Anti-Equality Laws", 
                    breaks = 0:6,  
                    labels = c("0 Laws", "1 Law", "2 Laws", "3 Laws", "4 Laws", "5 Laws", "6 Laws")) +
  theme_void() +
  theme(legend.position = "right",
        legend.background = element_rect(color = "black", fill = "grey90"), 
        legend.margin = margin(10, 5, 10, 5))

p2
```

```{r}
mich <- trans %>% 
  filter(st == "MI")
```

```{r}
states_2024 <- trans %>% filter(year == 2024)
num_states <- sum(states_2024$antidiscrim_score >= 1, na.rm = TRUE)
num_states
```

```{r}
states_2000 <- trans %>% filter(year == 2000)
num_states1 <- sum(states_2000$antidiscrim_score >= 1, na.rm = TRUE)
num_states1
```


```{r}
states_2024 <- trans %>% filter(year == 2024)
num_states2 <- sum(states_2024$antiequal_score >= 1, na.rm = TRUE)
num_states2
```


